### consulta contrato
GET  https://pncp.gov.br/api/consulta/v1/orgaos/62070362000106/compras/2026/21

### consulta item
GET https://pncp.gov.br/api/pncp/v1/orgaos/62070362000106/compras/2026/21/itens/2

### consulta contratos por página modalidade dispensa
GET https://pncp.gov.br/api/consulta/v1/contratacoes/proposta?dataFinal=20501231&uf=sp&codigoModalidadeContratacao=8&pagina=1

### consulta contratos por página modalidade pregão
GET https://pncp.gov.br/api/consulta/v1/contratacoes/proposta?dataFinal=20501231&uf=sp&codigoModalidadeContratacao=6&pagina=1

